### ISSUE TITLE
macos 15 requires local network entitlement and has issues with c-ares dns resolver

### ISSUE THREAD

**Issue by temporalu** [Chilledheart/yass#1076] opened 2024-09-01 02:14 UTC
I recently found out that YASS seems to have to disable all proxy settings under "System Settings>Wi-Fi>Details>Proxies" to start proxy connections on Mac, including HTTP, HTTPS and SOCKS proxies, otherwise it will prompt " Operation timed out" (See screenshot I pasted below).

1. I've tried opening YASS with "sudo open /Applications/yass.app" to try and resolve this issue, but it still doesn't work.
2. I've checked the firewall installed on my Mac (I'm using Little Snitch) and confirmed that it's not the firewall blocking YASS from establishing a proxy connection.
3. I've tried calling the Naive client (by which I mean https://github.com/klzgrad/naiveproxy) from the terminal and found that the issue doesn't appear here.

I'm wondering if the ability for YAAS to turn off all agent settings before starting the agent, or kill all threads that are trying to network, would solve this problem.

Disclaimer: I'm running YASS on macOS 15 dev beta, which may cause some unknown issues, but I'm guessing the issue may not be related to macOS 15? (I apologise if it matters, I'n not a professional about this)

![CleanShot 2024-09-01 at 09 06 39@2x](https://github.com/user-attachments/assets/125bf75d-d4bf-48ac-9289-e39ce4181a5a)

**Comment by Chilledheart** [comment] 2024-09-01 04:33
> I recently found out that YASS seems to have to disable all proxy settings under "System Settings>Wi-Fi>Details>Proxies" to start proxy connections on Mac, including HTTP, HTTPS and SOCKS proxies, otherwise it will prompt " Operation timed out" (See screenshot I pasted below).

No, yass doesn't follow the system proxy internally. Otherwise "System proxy" mode will make yass calling itself recursively.

`Operation Timed out` means it cannot resolving your server's IP address (probably DNS server is not reachable). Of course, you can follow the below steps to manullay skip the dns resovling.
1. Set `Server SNI` field to your server's hostname
2. Set `Server Host` field to your server's ip

> Disclaimer: I'm running YASS on macOS 15 dev beta, which may cause some unknown issues, but I'm guessing the issue may not be related to macOS 15? (I apologise if it matters, I'n not a professional about this)

Okay. Can you check if your macOS has enabled DoH or DoT? It could cause issues because the system DoH and DoT resolver might follow the system proxy settings.

For further debugging, you can attach your log. Open your terminal and type this with ENTER:
```
cat $TMPDIR/yass.INFO
```

**Comment by Chilledheart** [comment] 2024-09-01 04:48
<img width="810" alt="截屏2024-09-01 12 47 13" src="https://github.com/user-attachments/assets/fe2f13ad-c6a7-4572-a0da-ee8c516040e2">

I saw this. macOS now require new entitlement to access the Local Network. If your default DNS resolver server is local, then it might cause troubles because YASS cannot reach the local server without the new entitlement.

**Comment by Chilledheart** [comment] 2024-09-01 05:03
[yass-macos-release-x86_64-1.13.0-39-76e5cb9b-signed.dmg.zip](https://github.com/user-attachments/files/16827367/yass-macos-release-x86_64-1.13.0-39-76e5cb9b-signed.dmg.zip)

Here is the dmg with correct entitlement. It should work now. Please let me know if this dmg resolves your issue.

**Comment by Chilledheart** [comment] 2024-09-01 05:08
1. I've tried opening YASS with "sudo open /Applications/yass.app" to try and resolve this issue, but it still doesn't work.
> It doesn't matter.
2. I've checked the firewall installed on my Mac (I'm using Little Snitch) and confirmed that it's not the firewall blocking YASS from establishing a proxy connection.
> Nice check.
3. I've tried calling the Naive client (by which I mean https://github.com/klzgrad/naiveproxy) from the terminal and found that the issue doesn't appear here.
> Naiveproxy is unsigned so it won't be issue as it runs as unsandbox process, not an App. For yass, it is signed and notarizied as Developer ID Application as Apple recommends. So it folllows Apple's security requirements.

**Comment by Chilledheart** [comment] 2024-09-01 05:14
> Thanks for your reply, the problem is solved. :)
> 
> 1. I tried manually filling in the "Server SNI" and "Server Host" and turns out that the problem is indeed with the unreachable  DNS server.
> 2. Additionally, I've managed to check the DoH&DoT setting. The DNS configuration seems to be using standard DNS with nameservers set to 1.1.1.1 and 1.0.0.1, so that's not the problem I guess. (I paste down the outcome from Terminal in case you want to check it further)
> 
> [Terminal_outcome.md](https://github.com/user-attachments/files/16827413/Terminal_outcome.md)

Nice to hear that.

Can you also try the dmg provided in https://github.com/Chilledheart/yass/issues/1076#issuecomment-2323169302 ? So it will not be an issue even without the workaround.

**Comment by Chilledheart** [comment] 2024-09-01 05:37
> Okey.
> 
> There's no problem running the version [yass-macos-release-x86_64-1.13.0-39-76e5cb9b-signed.dmg.zip](https://github.com/user-attachments/files/16827367/yass-macos-release-x86_64-1.13.0-39-76e5cb9b-signed.dmg.zip) on my device when I manually define the 'Server Host' and 'Server SNI'. ![CleanShot 2024-09-01 at 14 19 41@2x](https://private-user-images.githubusercontent.com/122422616/363460679-24674fc1-d185-465c-8fa7-4743517b4ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjkyMDAsIm5iZiI6MTcyNTE2ODkwMCwicGF0aCI6Ii8xMjI0MjI2MTYvMzYzNDYwNjc5LTI0Njc0ZmMxLWQxODUtNDY1Yy04ZmE3LTQ3NDM1MTdiNGZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNTM1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzBjZjA0OWIyYWIxNjdkMzUxYzRiN2MxMGIxZTZlMDdiZGM2YWZhMDFiNGVkMTM0NWRkMTc1ODg5NWI1YmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DPLkDgPiAPK1KDpuCz4Uc8VMTACHlNlZBYhxqUXUBNA)
> 
> But it will runs into an "Operation timed out" problem if I assign these two parameters to my server host and blank.

Well, it seems the new entitlement doesn't work. If the behavious is expeced under macOS 15, I think it is better to disable c-ares dns resolver for macOS build then.

**Comment by Chilledheart** [comment] 2024-09-01 05:45
@temporalu can you try with the below dmg (signed as previous one) but with c-ares dns resolver disabled, which requires no new permission of local network (safer).

Intel's dmg
[yass-macos-release-x86_64-1.13.0-39-c14de2d8-signed.dmg.zip](https://github.com/user-attachments/files/16827500/yass-macos-release-x86_64-1.13.0-39-c14de2d8-signed.dmg.zip)

Apple silicon's dmg:

[yass-macos-release-arm64-1.13.0-39-c14de2d8-signed.dmg.zip](https://github.com/user-attachments/files/16827497/yass-macos-release-arm64-1.13.0-39-c14de2d8-signed.dmg.zip)

Thanks again.

**Closed** 2024-09-01 05:56 UTC

**Comment by Chilledheart** [comment] 2024-09-01 05:58
Great.

**Comment by Chilledheart** [comment] 2024-09-01 06:00
It makes sense as it provides new error code now! @temporalu 

We can leave this issue to apple safely.

**Comment by Chilledheart** [comment] 2024-09-01 06:06
<img width="787" alt="截屏2024-09-01 14 04 49" src="https://github.com/user-attachments/assets/b896b1d3-522e-499d-9e1e-442c46f4ea37">

You can find more information about Apple's DNS issues on below reddit issue and etc.

https://www.reddit.com/r/homelab/comments/vtv113/apple_devices_ignoring_dns_settings/
